[project]
name = "rft-grpo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.7.1",
    "transformers>=4.53.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.4",
]
